services:
  user-auth-cleanarch:
    build:
      context: .
      dockerfile: UserAuthCleanArch/Dockerfile
    container_name: user-auth-cleanarch
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      MYSQL_CONNECTION_STRING: Server=mysql;Port=3306;Database=user_auth;User=user;Password=1234;Allow User Variables=True;
      JWT_SECRET: change-this-secret-in-development
      JWT_ISSUER: UserAuth.CleanArch.API
      JWT_AUDIENCE: UserAuth.CleanArch.Client
    ports:
      - 5000:8080
    depends_on:
      - mysql

  catalog-service-mvc:
    build:
      context: .
      dockerfile: CatalogServiceMvc/Dockerfile
    container_name: catalog-service-mvc
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      POSTGRES_CONNECTION_STRING: Host=postgres;Port=5432;Database=catalog;Username=catalog;Password=1234
      JWT_SECRET: change-this-secret-in-development
      JWT_ISSUER: UserAuth.CleanArch.API
      JWT_AUDIENCE: UserAuth.CleanArch.Client
    ports:
      - 5001:8080
    depends_on:
      - user-auth-cleanarch
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql

volumes:
  mysql_data:
  postgres_data:
