services:
  catalog-service:
    build:
      context: ..
      dockerfile: CatalogServiceMvc/Dockerfile
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      JWT_SECRET: change-this-secret-in-development
      JWT_ISSUER: UserAuth.CleanArch.API
      JWT_AUDIENCE: UserAuth.CleanArch.Client
    ports:
      - 5001:8080
    depends_on:
      - cleanarch-api

  cleanarch-api:
    build:
      context: ..
      dockerfile: UserAuthCleanArch/UserAuth.CleanArch.API/Dockerfile
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:8080
      MONGODB_URI: mongodb://user:1234@mongo:27017/?authSource=admin
      MONGODB_DB: cleanarch
      JWT_SECRET: change-this-secret-in-development
      JWT_ISSUER: UserAuth.CleanArch.API
      JWT_AUDIENCE: UserAuth.CleanArch.Client
    ports:
      - 5000:8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://user:1234@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo

volumes:
  mongo_data:
